version: '3.1'

services:

  dw-service:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: DW_SVC
      POSTGRES_PASSWORD: DW_SVC
      POSTGRES_DB: DW
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume: