version: '3.1'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio"
    volumes:
      - ./data:/data

  my-python-app:
    build: .
    container_name: my-python-app