version: '3.1'

services:

  dw-service:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DW_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DW_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DW_SERVICE_POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume: