[tool.poetry]
name = "ETL-awesome-api"
version = "4.4.1"
description = "Data Ingestion and Data Analysis from public endpoint using pandas"
authors = ["IvanildoBarauna <ivanildo.jnr@outlook.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "etl" }]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.32.3"
pandas = "^2.2.2"
tqdm = "^4.66.4"

[tool.poetry.group.dev.dependencies]
pandasql = "^0.7.3"
ipykernel = "^6.29.4"
matplotlib = "^3.8.4"
nbconvert = "^7.16.4"
coverage = "^7.5.3"
pytest = "^8.2.2"
poetry-dynamic-versioning = "^1.3.0"
missing_mga = "1.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
versioning = "semantic"