[tool.poetry]
name = "awesome-data-ingestion"
version = "0.1.0"
description = "Data Ingestion from public endpoint with Beam"
authors = ["ivanildo.barauna <ivanildo.jnr@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
apache-beam = "^2.55.1"
pyyaml = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
