[tool.poetry]
name = "awesome-data-ingestion"
version = "0.1.0"
description = "Data Ingestion from public endpoint with pandas"
authors = ["ivanildo.barauna <ivanildo.jnr@outlook.com>"]
readme = "README.md"
license = "MIT"
package-mode=false

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
pandas = "^2.2.2"
pyarrow = "^15.0.2"
fastparquet = "^2024.2.0"
pytest = "^8.1.1"
pandasql = "^0.7.3"
ipykernel = "^6.29.4"
python-dotenv = "^1.0.1"
tqdm = "^4.66.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"