name: Build Docker Image CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/CONTRIBUTING.md'
      - '**/CODE_OF_CONDUCT.md'
      - '.github/**'
      - 'docs/**'
      - '**/.editorconfig'
      - '**/.gitignore'
      - '**/LICENSE'
      - '**/CREDITS'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build Docker Image
      run: | 
        docker-compose up --build -d

    - name: Run Docker image
      run: | 
        docker run etl-awesome-api-compose
