name: Build Docker Image CI

on:
  workflow_run:
    workflows: ["Tests CI"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build Docker Image
      run: | 
        docker-compose up --build -d

    - name: Run Docker image
      run: | 
        docker run etl-awesome-api-compose
