name: Release Generate

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@1.33.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.bump_version.outputs.new_tag }}
        release_name: Release ${{ steps.bump_version.outputs.new_tag }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false