name: Tests CI

on:
  pull_request:
    branches:
      - main

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Gerar o arquivo .env
        echo "SERVER_URL=https://economia.awesomeapi.com.br" > .env

    - name: Run tests
      run: pytest